<a href="https://colab.research.google.com/github/Jyoshnagundapu/2216134_AIML_BootCamp/blob/main/SpamSMSClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
#importing libraries
import pandas as pd
import numpy as np

In [39]:
df=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection',sep='\t',header=None,names=['label','message'])


In [40]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [41]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [43]:
df.shape

(5572, 2)

In [44]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [45]:
#data preprocessing
#method1-Label encoder done in malaria dataset

#method2
df['label']=df.label.map({'ham':0,'spam':1})

In [46]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [47]:
df.dropna(inplace=True)

In [48]:
df.shape

(5572, 2)

In [49]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [50]:
#Bag of words (BoW)
#DEMO of BoW with the help of countvectorizer
#define documents
documents=['Hello,how are you!',
           'each one,catch one.',
           'I am busy now.']

#Apply countvectorizer-import it from sklearn library

from sklearn.feature_extraction.text import CountVectorizer

count_vector=CountVectorizer() #calling method

In [51]:
#fit_transform or transform

count_vector.fit(documents)


CountVectorizer()

In [52]:
n=count_vector.get_feature_names()
n

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['am', 'are', 'busy', 'catch', 'each', 'hello', 'how', 'now', 'one', 'you']

In [53]:
doc_array=count_vector.transform(documents).toarray()


In [54]:
doc_array

array([[0, 1, 0, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 0, 2, 0],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 0]])

In [55]:
#converting this array to dataframe
freq_table=pd.DataFrame(data=doc_array,columns=n)

In [56]:
freq_table

am  are  busy  catch  each  hello  how  now  one  you
0   0    1     0      0     0      1    1    0    0    1
1   0    0     0      1     1      0    0    0    2    0
2   1    0     1      0     0      0    0    1    0    0

In [57]:
#load the data
#method1
X=df.iloc[:,-1:].values #independent-message column
Y=df.iloc[:,:-1].values #dependent-label column
#method2
#import numpy as np
#X1=np.array(df[['message']])
#Y1=np.array(df[['label']])

In [58]:
X

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [59]:
Y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [60]:
#Split the data into training data and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1,shuffle=True)

In [61]:
X_train.shape

(4457, 1)

In [62]:
X_test.shape

(1115, 1)

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
#Transform the Training data into freqq vectors and return the matrix
training_data=count_vector.fit_transform(X_train.flatten())
#Transform the Testing data into freq vectors and return the matrix
testing_data=count_vector.transform(X_test.flatten())

In [64]:
from sklearn.linear_model import LogisticRegression
a=LogisticRegression()
a.fit(training_data,Y_train)
y_pred=a.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",a.score(training_data,Y_train)*100)
print("Predicted value for testing data:",a.score(testing_data,Y_test)*100)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 99.75319721785955
Predicted value for testing data: 98.9237668161435


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) 
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,a.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 11 136]]
confusion matrix for traning data
[[3857    0]
 [  11  589]]


In [66]:
from sklearn.neighbors import KNeighborsClassifier
b=KNeighborsClassifier()
b.fit(training_data,Y_train)
y_pred=b.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",b.score(training_data,Y_train)*100)
print("Predicted value for testing data:",b.score(testing_data,Y_test)*100)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 93.56069104778999
Predicted value for testing data: 92.37668161434978


In [67]:
from sklearn.naive_bayes import MultinomialNB
c=MultinomialNB()
c.fit(training_data,Y_train)
y_pred=c.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",c.score(training_data,Y_train)*100)
print("Predicted value for testing data:",c.score(testing_data,Y_test)*100)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 99.23715503702041
Predicted value for testing data: 99.01345291479821


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [68]:
from sklearn.svm import SVC
d=SVC()
d.fit(training_data,Y_train)
y_pred=d.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",d.score(training_data,Y_train)*100)
print("Predicted value for testing data:",d.score(testing_data,Y_test)*100)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 99.50639443571909
Predicted value for testing data: 98.7443946188341


In [69]:
from sklearn.tree import DecisionTreeClassifier
e=DecisionTreeClassifier()
e.fit(training_data,Y_train)
y_pred=e.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",e.score(training_data,Y_train)*100)
print("Predicted value for testing data:",e.score(testing_data,Y_test)*100)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 100.0
Predicted value for testing data: 97.21973094170404


In [70]:
from sklearn.ensemble import RandomForestClassifier
f=RandomForestClassifier()
f.fit(training_data,Y_train)
y_pred=f.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",f.score(training_data,Y_train)*100)
print("Predicted value for testing data:",f.score(testing_data,Y_test)*100)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 100.0
Predicted value for testing data: 98.29596412556054
